[RFC] Signature help stoppable
puremourning/YouCompleteMe pull request #5
Opened 2019-10-11 18:52 UTC by bstaletic

This PR is supposed to accompany puremourning/ycmd-1#19.

The problem with this is that the response of `/signature_help_available` is a literal `True`, `False` or `None` and from there we get the following problems:

- In `client/base_request.py`, `_JsonResponse()` needs the `try`/`except` because "bool has no attribute result".
- In `client/signature_help.py`, class `SignatureHelpAvailableRequest`
  - `Done()` always returns `True`, so all of this is betting on the request getting its response before the timeout.
  - `Response()` just returns whatever `Start()` put into `self._response_future`.
  - `self._response_future` isn't really a "future".

Yeah, it's a terrible hack, so we need to change the request somewhat. I'm open for ideas. There's also the possibility that I missed something big.

2019-10-11 19:20 UTC, puremourning commented
If we change the response to be an object (which I recommended anyway) does it get easier?  Also any reason we’re not using a future? Just treat ‘not done’ as unknown (which we treat as false-for-now) but don’t send another request.

2019-10-11 21:30 UTC, bstaletic reviewed
Here's the update. We are using a future object now. 

There's still the question about how the response should look like. I'm not against returning an object, so does the following look okay?

```
{
  'value': V
}
```

Where `V` would be one of `'YES'`, `'NO'` and `'PENDING'`, similar to what you suggested.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-LqweIb74d_PyqdlJVpQ:barw1a)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[python/ycm/youcompleteme.py, line 120 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/5#-LqweWdZEm0lvcBcOvqd:-LqweWdZEm0lvcBcOvqe:b-4hp9ml) ([raw file](https://github.com/puremourning/youcompleteme/blob/8db92d170d54cd3590e1e65da17eaea70898f107/python/ycm/youcompleteme.py#L120)):*
> ```Python
>     self._latest_completion_request = None
>     self._latest_signature_help_request = None
>     self._latest_signature_available_request = None
> ```

This line is currently not used.
___
*[python/ycm/youcompleteme.py, line 347 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/5#-LqwehRF0GnQX-lFyhV8:-LqwehRF0GnQX-lFyhV9:b8g9gc3) ([raw file](https://github.com/puremourning/youcompleteme/blob/8db92d170d54cd3590e1e65da17eaea70898f107/python/ycm/youcompleteme.py#L347)):*
> ```Python
>       signature_help_available_request.Start()
>       while not signature_help_available_request.Done():
>         pass
> ```

I made this busy loop here to wait for the `/signature_request_available` to get the response.
Why? Because that was much easier than to juggle two closely related asyc requests. Otherwise it would require additional state to recognize the "response didn't come yet" case.


<!-- Sent from Reviewable.io -->

2019-10-12 07:40 UTC, bstaletic reviewed
I cleaned this up and updated to reflect the newer changes in puremourning/ycmd-1#19.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lqyu1Iu38pV8DQCrV7q:bdozymr)* status: 0 of 3 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2019-10-12 17:13 UTC, bstaletic commented
I found a bug with this one:

- Trigger signature help in a C++ file and exit insert mode.
- Open a file for which we don't have signature help.
  - This creates a state where `_latest_signature_help_request` still holds the response of the C++ request, since we never send a request for the non-supported filetype.
  - If the last C++ `/signature_help` response wasn't empty, it ends up showing on every character in the non-supported file.

My solution to this was to completely reset signature help, including setting `_latest_signature_help_request` to `None. (already in the PR)

An alternative approach to this would be to just return `{}` for signature help all the time if we are in a filetype for which `/signature_help_available` didn't return `'YES'`.

2019-10-12 17:50 UTC, puremourning reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bstaletic)

___
*[python/ycm/youcompleteme.py, line 347 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/5#-LqwehRF0GnQX-lFyhV8:-Lr02Sy97OxwaAo_HVVK:b-e9f1xs) ([raw file](https://github.com/puremourning/youcompleteme/blob/8db92d170d54cd3590e1e65da17eaea70898f107/python/ycm/youcompleteme.py#L347)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I made this busy loop here to wait for the `/signature_request_available` to get the response.
Why? Because that was much easier than to juggle two closely related asyc requests. Otherwise it would require additional state to recognize the "response didn't come yet" case.
</blockquote></details>

I think we should absolutely _not_ do this busy wait. This will block the Vim GUI which we never want to do.

IMO we should just drop this SendSIgnatureHelpRequest and wait for the next key(s) to be typed, as in just don't do any signature help until we know that it's supported. We can even kick off the first "signature help available" request in OnBufferVisit or whatever which means it might be done by the time the meatbag has typed `i` or whatever to get into insert mode

e.g.

* in signature_help client .py file

```python
class SigHelpAvailableByFileType(dict):
  def __missing__( self, filetype ):
    request = self[ filetype ] = SignatureHelpAvailableRequest( filetype )
    return request 

class SignatureHelpAvailableRequest:
    def __init__ (.. ):
        ...
        self.Start()
```

* in youcompleteme.py:

```python

# in __init__
self._signature_help_available_requests = SigHelpAvailableByFileType()

# in buffer visit (or some other appropriate place), cause it to send the request
self._signature_help_avaioable_request[ filetype ].Done()

# elsewhere ...
if not self._signature_help_abailable_request[ filetype ].Done():
  return
# use self._signature_help_available_request[ filetype ].Response()
```


<!-- Sent from Reviewable.io -->

2019-10-12 19:35 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5)* status: 0 of 4 files reviewed, all discussions resolved

___
*[python/ycm/youcompleteme.py, line 347 at r1](https://reviewable.io/reviews/puremourning/youcompleteme/5#-LqwehRF0GnQX-lFyhV8:-Lr0SpZiCwGTVF3flfNM:b-896fix) ([raw file](https://github.com/puremourning/youcompleteme/blob/8db92d170d54cd3590e1e65da17eaea70898f107/python/ycm/youcompleteme.py#L347)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think we should absolutely _not_ do this busy wait. This will block the Vim GUI which we never want to do.

IMO we should just drop this SendSIgnatureHelpRequest and wait for the next key(s) to be typed, as in just don't do any signature help until we know that it's supported. We can even kick off the first "signature help available" request in OnBufferVisit or whatever which means it might be done by the time the meatbag has typed `i` or whatever to get into insert mode

e.g.

* in signature_help client .py file

```python
class SigHelpAvailableByFileType(dict):
  def __missing__( self, filetype ):
    request = self[ filetype ] = SignatureHelpAvailableRequest( filetype )
    return request 

class SignatureHelpAvailableRequest:
    def __init__ (.. ):
        ...
        self.Start()
```

* in youcompleteme.py:

```python

# in __init__
self._signature_help_available_requests = SigHelpAvailableByFileType()

# in buffer visit (or some other appropriate place), cause it to send the request
self._signature_help_avaioable_request[ filetype ].Done()

# elsewhere ...
if not self._signature_help_abailable_request[ filetype ].Done():
  return
# use self._signature_help_available_request[ filetype ].Response()
```


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-12 22:08 UTC, puremourning requested changes
I think this starts to LGTM!

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr1-E97-pJo72DHBWop:b-bzgx5t)* status: all files reviewed, 1 unresolved discussion (waiting on @bstaletic)

___
*[python/ycm/youcompleteme.py, line 532 at r2](https://reviewable.io/reviews/puremourning/youcompleteme/5#-Lr0zC6x68ZJsMkgpJz-:-Lr0zC6x68ZJsMkgpJz0:b-gqc06a) ([raw file](https://github.com/puremourning/youcompleteme/blob/753e2892e9a3b1a726d45aabd6d73e5423b2355a/python/ycm/youcompleteme.py#L532)):*
> ```Python
>   def OnBufferVisit( self ):
>     filetype = vimsupport.CurrentFiletypes()[ 0 ]
>     self._signature_help_available_requests[ filetype ].Start( filetype )
> ```

it's possible that we get buffer visit while some existing available request for this filetype already active, we shouldn't start a new one in that case, i.e. only do this if the request is not 'Done()' (also the call to the constructor calls Start, so actually this code should probably be: `self._signature)help_available_requests[ filetype ].Done()` with a comment that this is intended to fire a request if we didn't already.


<!-- Sent from Reviewable.io -->

2019-10-12 22:47 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @puremourning)

___
*[python/ycm/youcompleteme.py, line 532 at r2](https://reviewable.io/reviews/puremourning/youcompleteme/5#-Lr0zC6x68ZJsMkgpJz-:-Lr15zU3EySdhV8gFHNS:b-896fix) ([raw file](https://github.com/puremourning/youcompleteme/blob/753e2892e9a3b1a726d45aabd6d73e5423b2355a/python/ycm/youcompleteme.py#L532)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

it's possible that we get buffer visit while some existing available request for this filetype already active, we shouldn't start a new one in that case, i.e. only do this if the request is not 'Done()' (also the call to the constructor calls Start, so actually this code should probably be: `self._signature)help_available_requests[ filetype ].Done()` with a comment that this is intended to fire a request if we didn't already.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-13 15:51 UTC, puremourning reviewed
Sorry I rebased my branch, which has confused reviewable. 

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr4oEmi7bpHOthil4uW:b-i9jixd)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2019-10-13 16:27 UTC, bstaletic reviewed
It's not reviewable who got confused. It's git. These merge conflicts will take a bit before I resolve them.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr4wONI-0XivlOGsagG:b-ifn0d4)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2019-10-13 17:19 UTC, bstaletic reviewed
Alright, I rebased this thing, but now the CI is failing because it can't find ycmd commit 31d3137, which is what's checked in here:
https://github.com/puremourning/YouCompleteMe/tree/signature-help/third_party

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr56Te25GtGPjfMrcVD:b45dgga)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2019-10-13 17:33 UTC, puremourning commented
oh bother. I have pushed my branches now which should all exist. too many forks, too many branches.

2019-10-13 17:40 UTC, bstaletic reviewed
Let's see if another rebase helped.

> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr5CHYbDJQIIdtnxIMy:byn6zxj)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2019-10-14 13:09 UTC, puremourning approved these changes
I'll give this a spin. Thanks so much.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/puremourning/youcompleteme/5#-:-Lr9NjOl5i0eGlTR8RAE:bhhun3x)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-18 21:50 UTC, merged